// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/pages': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pages.post').default>>>>
    }
    '/api/pages/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pages/[id].get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@3.21.8_better-sqlite3@11.10.0_db0@0.3.4_better-sqlite3@11.10.0_drizz_b8170fdc8a71fe4000c10de90e80f501/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}